export default {
  ezpapelWebsiteVersion: '20240724A',
  appName: process.env.MIX_APP_NAME,
  appURL: 'https://ezpapel.com',
  trialDays: process.env.MIX_TRIAL_DAYS,
  // openChatForSpecificCompanyIds: [23, 36], //use for visible chat for company id
  hidefunctionalitiesForSpecificCompanyIds: 85,
  showFuelCardForSpecificCompanyId: [36],
  showBrokerModeForSpecificCompanyIds: [
    23, 87, 92, 110, 118, 123, 134, 138, 141, 160, 164, 165, 166, 183, 185, 186,
  ],
  hideLoadChargesForCompanyId: 90,
  showCustomizeDriverPayTypeOnlyForCompanyIdGreaterThanOrEqualTo: 186,
  // Company Ids which have access Default GL Account in CustomFields popup and Pay To Code in Tags form
  companiesWithPayToCodeNDefaultGLAccountAccess: [36, 76],
  companiesWithCostCodeEnabled: [112, 36],
  showBillToCodeAsJobCode: [112],
  companiesWithT3Access: [], //[112, 36], No longer used.
  showTagNumberPrefix: [23, 36, 143, 166],
  showSafetyTab: [23, 32, 143, 166, 182, 183, 186],
  useAuthorizeNetForManualInvoice: [36, 85],
  safetyCustomFieldLabels: [143],
  onlyUseSafetyTab: [143],
  additionalDisclaimerForCompanies: [118],
  anotherAdditionalDisclaimerForCompanies: [315],
  showCompanyInternalReferenceForCompanies: [36, 76, 92, 160],
  publicFuelPricesCacheTimestamp: 14400000, // 4 hours cache time
  dispatchListShowCompanyPickAndDeliveryNumbers: [36, 165],
  customReportsEnabled: [36, 76, 286],
  companiesWithShipperReceiverTimeHighlight: [36, 286],
  listDefaultTabCompanies: [36, 76],
  companiesWithSpreadsheetBatchActionsAccess: [23, 307],
  stageTrailerLocationEnabled: [307],
  companiesWithRoundedMilesToInteger: [76],
  mileBasedHaulingFeeCalculationDict: Object.freeze({
    companies: [307],
    /**
     * Note: Position is important
     *
     * Changing the position will affect result of calculation
     * As it is traversing from the lowest to the highest value
     * of equivalence
     */
    calculationRefs: [
      { flatFee: 500, lessThan: 51 },
      { flatFee: 600, lessThan: 76 },
      { flatFee: 700, lessThan: 101 },
      { flatFee: 800, lessThan: 151 },
      { flatFee: -1, lessThan: Infinity },
    ],
  }),
  authorizeNetAcceptJsUrl: {
    test: 'https://jstest.authorize.net/v1/Accept.js',
    prod: 'https://js.authorize.net/v1/Accept.js',
  },
  truckingDirectoryCarrierDetailUrl:
    process.env.NODE_ENV === 'production'
      ? 'https://truckpedia.io/truckingDirectory/viewDetail?'
      : 'http://localhost:5173/truckingDirectory/viewDetail?',

  all: 'all',
  parent: 'parent',

  oAuthGoogleClientId: process.env.MIX_GOOGLE_OAUTH_CLIENT_ID,

  idle_user_time: 864000, // value in seconds. ex. 60 x 20 = 1200 sec (20 min)

  weight_unit: { lbs: 1, tons: 2, kg: 3 },

  quantity_unit: {
    pallets: 1,
    crates: 2,
    hours: 3,
    days: 4,
    miles: 5,
    yards: 6,
    feet: 7,
    cases: 8,
    gallons: 9,
    pieces: 10,
  },

  roles: {
    super_admin: 'super_admin',
    admin: 'admin',
    driver: 'driver',
    dispatcher: 'dispatcher',
    warehouse_operator: 'warehouse_operator',
    tag_operator: 'tag_operator',
    maintenance: 'maintenance',
  },

  status: {
    load: {
      open: 'open',
      assign: 'assign',
      in_transit: 'in_transit',
      delivered: 'delivered',
      invoice_created: 'invoice_created',
      invoice_sent: 'payment_requested', //'invoice_sent',
      invoice_paid: 'invoice_paid',
      deleted: 'deleted',
      canceled: 'canceled',
    },

    nodeLoadToLabel: {
      open: 'Open',
      assign: 'Assigned',
      inTransit: 'In Transit',
      delivered: 'Delivered',
      invoiceCreated: 'Invoice Generated',
      paymentRequested: 'Payment Requested',
      invoicePaid: 'Paid',
      canceled: 'Canceled',
    },

    nodeLoadWithLabels: [
      { label: 'Open', value: 'open' },
      { label: 'Assigned', value: 'assign' },
      { label: 'In Transit', value: 'inTransit' },
      { label: 'Delivered', value: 'delivered' },
      { label: 'Invoice Generated', value: 'invoiceCreated' },
      { label: 'Payment Requested', value: 'paymentRequested' },
      { label: 'Paid', value: 'invoicePaid' },
      { label: 'Canceled', value: 'canceled' },
    ],

    loadWithLabels: [
      { label: 'Open', value: 'open' },
      { label: 'Assigned', value: 'assign' },
      { label: 'In Transit', value: 'in_transit' },
      { label: 'Delivered', value: 'delivered' },
      { label: 'Invoice Generated', value: 'invoice_created' },
      { label: 'Payment Requested', value: 'payment_requested' },
      { label: 'Paid', value: 'invoice_paid' },
      { label: 'Canceled', value: 'canceled' },
    ],

    manualInvoiceLabels: [
      { label: 'Paid', value: 'paid' },
      { label: 'Draft', value: 'draft' },
      { label: 'Requested', value: 'requested' },
    ],

    loadContainerStatuses: [
      { label: 'Empty', value: 'empty' },
      { label: 'Loaded', value: 'loaded' },
    ],

    loadContainerLocation: [
      { label: 'Shipper', value: 's' },
      { label: 'Receiver', value: 'r' },
      { label: 'Leg', value: 'l' },
      { label: 'Terminal', value: 't' },
    ],

    load_driver: {
      assign: 'assign',
      accepted: 'accepted',
      load_started: 'load_started',
      picked_up_load: 'picked_up_load',
      delivered: 'delivered',
      handed_over: 'handed_over',
      ready_to_handover: 'ready_to_handover',
      end_load: 'end_load',
    },

    load_truck_direction: { inbound: 'inbound', outbound: 'outbound' },

    subscription: {
      in_active: 'in_active',
      active: 'active',
      suspended: 'suspended',
      canceled: 'canceled',
    },
  },

  planning: {
    equipmentTypes: [
      { title: 'Van', value: 'van' },
      { title: 'Reefer', value: 'reefer' },
      { title: 'Flatbed', value: 'flatbed' },
      { title: 'Step Deck', value: 'stepDeck' },
      { title: 'Power Only', value: 'powerOnly' },
      { title: 'Conestoga', value: 'conestoga' },
      { title: 'Box Truck', value: 'boxTruck' },
      { title: 'Sprinter', value: 'sprinter' },
      { title: 'Drayage', value: 'drayage' },
      { title: 'RGN', value: 'rgn' },
      { title: 'Car Hauling', value: 'carHauling' },
    ],
  },

  marketplace: {
    equipmentTypes: [
      { title: 'Van', value: 'van' },
      { title: 'Reefer', value: 'reefer' },
      { title: 'Flatbed', value: 'flatbed' },
      { title: 'Step Deck', value: 'stepDeck' },
      { title: 'Power Only', value: 'powerOnly' },
      { title: 'Conestoga', value: 'conestoga' },
      { title: 'Box Truck', value: 'boxTruck' },
      { title: 'Sprinter', value: 'sprinter' },
      { title: 'Drayage', value: 'drayage' },
      { title: 'RGN', value: 'rgn' },
      { title: 'Car Hauling', value: 'carHauling' },
      { title: 'Intermodal', value: 'intermodal' },
    ],
  },

  equipment_type: {
    dry_van_53: '53_dry_van',
    reefer_53: '53_reefer',
    flatbed: 'flatbed',
    power_only: 'power_only',
    dry_van_48: '48_dry_van',
    reefer_48: '48_reefer',
    van_22: '22_van',
    cargo_van: 'cargo_van',
    hot_shot: 'hot_shot',
    box_truck: 'box_truck',
    load_out: 'load_out',
    step_deck: 'step_deck',
    straight_van: 'straight_van',
    tanker: 'tanker',
    curtain_van: 'curtain_van',
    vented_van: 'vented_van',
    dry_container_20: '20_dry_container',
    reefer_container_20: '20_reefer_container',
    dry_container_40: '40_dry_container',
    reefer_container_40: '40_reefer_container',
    dry_container_45: '45_dry_container',
    reefer_container_45: '45_reefer_container',
    lowboy: 'lowboy',
    landoll: 'landoll',
  },

  equipmentTypeOptions: [
    { title: "53' Dry Van", value: '53_dry_van' },
    { title: "53' Reefer", value: '53_reefer' },
    { title: 'Flatbed', value: 'flatbed' },
    { title: 'Power Only', value: 'power_only' },
    { title: "48' Dry Van", value: '48_dry_van' },
    { title: "48' Reefer", value: '48_reefer' },
    { title: "22' Van", value: '22_van' },
    { title: 'Cargo Van', value: 'cargo_van' },
    { title: 'Hot Shot', value: 'hot_shot' },
    { title: 'Box Truck', value: 'box_truck' },
    { title: 'Load-Out', value: 'load_out' },
    { title: 'Step Deck', value: 'step_deck' },
    { title: 'Straight Van', value: 'straight_van' },
    { title: 'Tanker', value: 'tanker' },
    { title: 'Curtain Van', value: 'curtain_van' },
    { title: 'Vented Van', value: 'vented_van' },
    {
      title: "20' Dry Container",
      value: '20_dry_container',
    },
    {
      title: "20' Reefer Container",
      value: '20_reefer_container',
    },
    {
      title: "40' Dry Container",
      value: '40_dry_container',
    },
    {
      title: "40' Reefer Container",
      value: '40_reefer_container',
    },
    {
      title: "45' Dry Container",
      value: '45_dry_container',
    },
    {
      title: "45' Reefer Container",
      value: '45_reefer_container',
    },
    { title: 'Lowboy', value: 'lowboy' },
    { title: 'Landoll', value: 'landoll' },
  ],

  trailer_type: { 'Walking Floor': 1, Dump: 2, Belt: 3 },

  driver_pay_type: {
    per_mile: 'per_mile',
    hourly: 'hourly',
    percentage: 'percentage',
  },

  driver_file_type: {
    driver_licence: 'driver_licence',
    driver_medical_card: 'driver_medical_card',
  },

  load_pay_percentage_of: {
    hauling_fees: 'hauling_fees',
    total_income: 'total_income',
    hauling_plus_fuel_surcharge: 'hauling_plus_fuel_surcharge',
  },

  loadImage: {
    purpose: {
      load_start_odometer: 'load_start_odometer',
      load_end_odometer: 'load_end_odometer',
      load_picked_up: 'load_picked_up',
      load_delivered: 'load_delivered',
      load_handover_odometer: 'load_handover_odometer',
      load_pod: 'load_pod',
      load_pod_admin: 'load_pod_admin', // pod upload by admin
      load_image_admin: 'load_image_admin', // image upload by admin
    },
  },

  truck_ownership: {
    company_truck: 'Company Truck',
    owner_operator: 'Owner Operator',
    leased: 'Leased',
  },

  trailer_ownership: {
    company_trailer: 'Company Trailer',
    owner_operator: 'Owner Operator',
    leased: 'Leased',
  },

  S3FilePath: {
    loadImages: 'load',
    loadPOD: 'load',
    load_rate_confirmations: 'load',
    load_invoice: 'invoices',
    maintenances: 'maintenances',
  },

  /*
   * Google Map Autocomplete Options
   */
  googleMapAutoCompleteOptions: {
    fields: ['geometry', 'formatted_address', 'address_components'],
  },

  /*
   * Company Features To Access Options
   */
  companyFeaturesToAccessOptions: [
    { label: 'broker mode for carrier', value: 'brokerModeForCarrier' },
    {
      label: 'chatGPT to parse load tenders',
      value: 'chatGptForLoadTenderParser',
    },
    { label: 'safety', value: 'safety' },
    { label: 'quote (Obsolete, use Marketplace instead)', value: 'quote' },
    { label: 'Marketing: email campaign', value: 'marketing' },
    { label: 'Marketing: CRM', value: 'crm' },
    { label: 'Basic TMS', value: 'basic' },
    { label: 'No TMS', value: 'noTms' },
    { label: 'Marketplace', value: 'marketplace' },
  ],

  /**
   * Stripe
   */
  stripe: {
    // Stripe Public Key
    key: process.env.MIX_STRIPE_KEY,

    // Elements Style
    style: { base: { color: '#32325d' } },
  },

  /**
   * PDF PARSE KEY
   */
  pdfParser: {
    baseURL: process.env.MIX_PDF_PARSE_BASE_URL,
    key: process.env.MIX_PDF_PARSE_KEY,
  },

  state_list: [
    { text: 'AL', value: 1 },
    { text: 'AK', value: 2 },
    { text: 'AZ', value: 3 },
    { text: 'AR', value: 4 },
    { text: 'CA', value: 5 },
    { text: 'CO', value: 6 },
    { text: 'CT', value: 7 },
    { text: 'DC', value: 8 },
    { text: 'DE', value: 9 },
    { text: 'FL', value: 10 },
    { text: 'GA', value: 11 },
    { text: 'HI', value: 12 },
    { text: 'ID', value: 13 },
    { text: 'IL', value: 14 },
    { text: 'IN', value: 15 },
    { text: 'IA', value: 16 },
    { text: 'KS', value: 17 },
    { text: 'KY', value: 18 },
    { text: 'LA', value: 19 },
    { text: 'ME', value: 20 },
    { text: 'MD', value: 21 },
    { text: 'MA', value: 22 },
    { text: 'MI', value: 23 },
    { text: 'MN', value: 24 },
    { text: 'MS', value: 25 },
    { text: 'MO', value: 26 },
    { text: 'MT', value: 27 },
    { text: 'NE', value: 28 },
    { text: 'NV', value: 29 },
    { text: 'NH', value: 30 },
    { text: 'NJ', value: 31 },
    { text: 'NM', value: 32 },
    { text: 'NY', value: 33 },
    { text: 'NC', value: 34 },
    { text: 'ND', value: 35 },
    { text: 'OH', value: 36 },
    { text: 'OK', value: 37 },
    { text: 'OR', value: 38 },
    { text: 'PA', value: 39 },
    { text: 'PR', value: 40 },
    { text: 'RI', value: 41 },
    { text: 'SC', value: 42 },
    { text: 'SD', value: 43 },
    { text: 'TN', value: 44 },
    { text: 'TX', value: 45 },
    { text: 'UT', value: 46 },
    { text: 'VT', value: 47 },
    { text: 'VA', value: 48 },
    { text: 'WA', value: 49 },
    { text: 'WV', value: 50 },
    { text: 'WI', value: 51 },
    { text: 'WY', value: 52 },
  ],

  equipmentClassesOption: [
    { text: 'Vans, Standard', value: 'V' },
    { text: 'Flatbeds', value: 'F' },
    { text: 'Reefers', value: 'R' },
    { text: 'Conestoga', value: 'N' },
    { text: 'Containers', value: 'C' },
    { text: 'Decks, Specialized', value: 'K' },
    { text: 'Decks, Standard', value: 'D' },
    { text: 'Dry Bulk', value: 'B' },
    { text: 'Hazardous Materials', value: 'Z' },
    { text: 'Other Equipment', value: 'O' },
    { text: 'Tankers', value: 'T' },
    { text: 'Vans, Specialized', value: 'S' },
  ],

  truckstopEquipmentTypesOptions: [
    { text: 'ANY', value: 'ANY' },
    { text: '2F', value: '2F' },
    { text: 'ANIM', value: 'ANIM' },
    { text: 'AUTO', value: 'AUTO' },
    { text: 'B-TR', value: 'B-TR' },
    { text: 'BDMP', value: 'BDMP' },
    { text: 'BEAM', value: 'BEAM' },
    { text: 'BELT', value: 'BELT' },
    { text: 'BOAT', value: 'BOAT' },
    { text: 'CH', value: 'CH' },
    { text: 'CONG', value: 'CONG' },
    { text: 'CONT', value: 'CONT' },
    { text: 'CV', value: 'CV' },
    { text: 'DA', value: 'DA' },
    { text: 'DD', value: 'DD' },
    { text: 'DDE', value: 'DDE' },
    { text: 'DUMP', value: 'DUMP' },
    { text: 'ENDP', value: 'ENDP' },
    { text: 'F', value: 'F' },
    { text: 'FA', value: 'FA' },
    { text: 'FEXT', value: 'FEXT' },
    { text: 'FINT', value: 'FINT' },
    { text: 'FO', value: 'FO' },
    { text: 'FRV', value: 'FRV' },
    { text: 'FSD', value: 'FSD' },
    { text: 'FSDV', value: 'FSDV' },
    { text: 'FV', value: 'FV' },
    { text: 'FVR', value: 'FVR' },
    { text: 'FVV', value: 'FVV' },
    { text: 'FVVR', value: 'FVVR' },
    { text: 'FWS', value: 'FWS' },
    { text: 'HOPP', value: 'HOPP' },
    { text: 'HS', value: 'HS' },
    { text: 'HTU', value: 'HTU' },
    { text: 'LAF', value: 'LAF' },
    { text: 'LB', value: 'LB' },
    { text: 'LBO', value: 'LBO' },
    { text: 'LDOT', value: 'LDOT' },
    { text: 'LIVE', value: 'LIVE' },
    { text: 'MAXI', value: 'MAXI' },
    { text: 'MBHM', value: 'MBHM' },
    { text: 'PNEU', value: 'PNEU' },
    { text: 'PO', value: 'PO' },
    { text: 'R', value: 'R' },
    { text: 'RFV', value: 'RFV' },
    { text: 'RGN', value: 'RGN' },
    { text: 'RGNE', value: 'RGNE' },
    { text: 'RINT', value: 'RINT' },
    { text: 'ROLL', value: 'ROLL' },
    { text: 'RPD', value: 'RPD' },
    { text: 'RV', value: 'RV' },
    { text: 'RVF', value: 'RVF' },
    { text: 'SD', value: 'SD' },
    { text: 'SDL', value: 'SDL' },
    { text: 'SDO', value: 'SDO' },
    { text: 'SDRG', value: 'SDRG' },
    { text: 'SPEC', value: 'SPEC' },
    { text: 'SV', value: 'SV' },
    { text: 'TANK', value: 'TANK' },
    { text: 'V', value: 'V' },
    { text: 'V-OT', value: 'V-OT' },
    { text: 'VA', value: 'VA' },
    { text: 'VB', value: 'VB' },
    { text: 'VCAR', value: 'VCAR' },
    { text: 'VF', value: 'VF' },
    { text: 'VFR', value: 'VFR' },
    { text: 'VINT', value: 'VINT' },
    { text: 'VIV', value: 'VIV' },
    { text: 'VIVR', value: 'VIVR' },
    { text: 'VLG', value: 'VLG' },
    { text: 'VM', value: 'VM' },
    { text: 'VR', value: 'VR' },
    { text: 'VRDD', value: 'VRDD' },
    { text: 'VRF', value: 'VRF' },
    { text: 'VV', value: 'VV' },
    { text: 'VVR', value: 'VVR' },
    { text: 'WALK', value: 'WALK' },
  ],

  loadMatchingManualSearchTypeOptions: [
    { text: 'Van', value: 'V' },
    { text: 'Reefer', value: 'R' },
    { text: 'Flatbed', value: 'F' },
    { text: 'Power Only', value: 'Power Only' },
    { text: 'Box Truck', value: 'Box Truck' },
  ],

  spreadsheetLoadPredefinedColumns: {
    'Load #': 'loadNumber',
    'Load Reference': 'loadReference',
    'Load Status': 'loadStatus',
    'Load Amount': 'loadAmount',
    Miles: 'loadDistance',
    'Empty Miles': 'loadEmptyDistance',
    Customer: 'loadCustomer',
    'Bill To Code': 'loadBillToCode',
    Tag: 'loadTag',
    Dispatcher: 'loadDispatcher',
    Shipper: 'loadShipperNames',
    'Pick Up': 'loadPickUpLocation',
    'Ship Date': 'loadShipDate',
    Receiver: 'loadReceiverNames',
    Delivery: 'loadDeliveryLocation',
    'Del. Date': 'loadDeliveryDate',
    Drivers: 'loadDrivers',
    'Driver HOS': 'loadDriverHos',
    'Driver Pay': 'loadDriverPay',
    Notes: 'loadDispatcherNotes',
    Container: 'loadContainer',
    'Container Status': 'loadContainerStatus',
    'Container Location': 'loadContainerLocation',
    'Equipment #': 'loadEquipmentNumber',
    'Freight Description': 'loadFreightDescription',
    Weight: 'loadTotalWeight',
    Truck: 'loadTrucks',
    Trailer: 'loadTrailers',
    Chassis: 'loadChassis',
    POD: 'loadPod',
    'Invoice Date': 'loadInvoiceDate',
    'Third Party Carrier': 'loadThirdPartyCarrier',
    // 'Find Carriers': 'loadFindCarriers',
    'Rate For Third Party': 'loadThirdPartyCarrierRate',
    'Rate Con For Third Party': 'loadThirdPartyCarrierRateCon',
    'BOL For Third Party': 'loadThirdPartyCarrierBol',
    'Gross Profit (Brokered Load)': 'loadGrossProfitBrokeredLoad',
    'Gross Profit % (Brokered Load)': 'loadGrossProfitPercentageBrokeredLoad',
    'Hauling Fee': 'loadHaulingFee',
    'Fuel Surcharge': 'loadFuelSurcharge',
    'Accessorial Fees': 'loadAccessorialFees',
    'Accessorial Deductions': 'loadAccessorialDeductions',
    'Hauling Fee For Third Party': 'loadThirdPartyCarrierHaulingFee',
    'Fuel Surcharge For Third Party': 'loadThirdPartyCarrierFuelSurcharge',
    'Accessorial Fees For Third Party': 'loadThirdPartyCarrierAccessorialFees',
    'Accessorial Deductions For Third Party':
      'loadThirdPartyCarrierAccessorialDeductions',
    '1st Ship Date': 'loadFirstShipDate',
    'Last Del. Date': 'loadLastDeliveryDate',
    '1st Shipper Name': 'loadFirstShipperName',
    '1st Shipper Address': 'loadFirstShipperAddress',
    '1st Shipper City': 'loadFirstShipperCity',
    '1st Shipper State': 'loadFirstShipperState',
    '1st Shipper ZIP Code': 'loadFirstShipperZipCode',
    'Last Receiver Name': 'loadLastReceiverName',
    'Last Receiver Address': 'loadLastReceiverAddress',
    'Last Receiver City': 'loadLastReceiverCity',
    'Last Receiver State': 'loadLastReceiverState',
    'Last Receiver ZIP Code': 'loadLastReceiverZipCode',
    'Internal Reference': 'loadInternalReference',
    'Driver Delivery Status': 'loadDriverUnloadedStatus',
  },

  spreadsheetColFilterOperators: {
    loadShipDate: ['is'],
    loadDeliveryDate: ['is'],
    loadDirection: ['is'],
    loadShipper: ['contains'],
    loadReceiver: ['contains'],
    loadPickupState: ['isAnyOf'],
    loadDeliveryState: ['isAnyOf'],
    loadLeg: ['contains'],
    loadDriver: ['isAnyOf'],
    loadTruck: ['isAnyOf'],
    loadTrailer: ['isAnyOf'],
    loadDispatcher: ['isAnyOf'],
    loadTag: ['isAnyOf'],
    loadCustomer: ['isAnyOf'],
    loadStatus: ['isAnyOf'],
    loadThirdPartyCarrier: ['isAnyOf', 'isEmpty', 'isNotEmpty'],
    loadContainerStatus: ['is'],
    loadContainerLocation: ['isAnyOf'],
  },

  weekDays: [
    { text: 'Su', value: 0 },
    { text: 'M', value: 1 },
    { text: 'Tu', value: 2 },
    { text: 'W', value: 3 },
    { text: 'Th', value: 4 },
    { text: 'F', value: 5 },
    { text: 'Sa', value: 6 },
  ],

  monthDays: [
    { text: '1st', value: 1 },
    { text: '2nd', value: 2 },
    { text: '3rd', value: 3 },
    { text: '4th', value: 4 },
    { text: '5th', value: 5 },
    { text: '6th', value: 6 },
    { text: '7th', value: 7 },
    { text: '8th', value: 8 },
    { text: '9th', value: 9 },
    { text: '10th', value: 10 },
    { text: '11th', value: 11 },
    { text: '12th', value: 12 },
    { text: '13th', value: 13 },
    { text: '14th', value: 14 },
    { text: '15th', value: 15 },
    { text: '16th', value: 16 },
    { text: '17th', value: 17 },
    { text: '18th', value: 18 },
    { text: '19th', value: 19 },
    { text: '20th', value: 20 },
    { text: '21st', value: 21 },
    { text: '22nd', value: 22 },
    { text: '23rd', value: 23 },
    { text: '24th', value: 24 },
    { text: '25th', value: 25 },
    { text: '26th', value: 26 },
    { text: '27th', value: 27 },
    { text: '28th', value: 28 },
    { text: '29th', value: 29 },
    { text: '30th', value: 30 },
    { text: '31st', value: 31 },
    { text: 'last day', value: 32 },
  ],

  spreadSheetColorPickerPallet: [
    '#000000',
    '#434343',
    '#666666',
    '#999999',
    '#b7b7b7',
    '#cccccc',
    '#d9d9d9',
    '#efefef',
    '#f3f3f3',
    '#ffffff',
    '#980000',
    '#ff0000',
    '#ff9900',
    '#ffff00',
    '#00ff00',
    '#00ffff',
    '#4a86e8',
    '#0000ff',
    '#9900ff',
    '#ff00ff',
    '#e6b8af',
    '#f4cccc',
    '#fce5cd',
    '#fff2cc',
    '#d9ead3',
    '#d0e0e3',
    '#c9daf8',
    '#cfe2f3',
    '#d9d2e9',
    '#ead1dc',
    '#dd7e6b',
    '#ea9999',
    '#f9cb9c',
    '#ffe599',
    '#b6d7a8',
    '#a2c4c9',
    '#a4c2f4',
    '#9fc5e8',
    '#b4a7d6',
    '#d5a6bd',
    '#cc4125',
    '#e06666',
    '#f6b26b',
    '#ffd966',
    '#93c47d',
    '#76a5af',
    '#6d9eeb',
    '#6fa8dc',
    '#8e7cc3',
    '#c27ba0',
    '#a61c00',
    '#cc0000',
    '#e69138',
    '#f1c232',
    '#6aa84f',
    '#45818e',
    '#3c78d8',
    '#3d85c6',
    '#674ea7',
    '#a64d79',
    '#85200c',
    '#990000',
    '#b45f06',
    '#bf9000',
    '#38761d',
    '#134f5c',
    '#1155cc',
    '#0b5394',
    '#351c75',
    '#741b47',
    '#5b0f00',
    '#660000',
    '#783f04',
    '#7f6000',
    '#274e13',
    '#0c343d',
    '#1c4587',
    '#073763',
    '#20124d',
    '#4c1130',
  ],

  PRIORITIES_LIST: [
    { label: 'Low', value: 'low' },
    { label: 'Medium', value: 'medium' },
    { label: 'High', value: 'high' },
  ],

  maintenanceStatus: {
    reported: 'Reported',
    scheduled: 'Scheduled',
    in_service: 'In Service',
    completed: 'Completed',
  },

  // Commonly used file extensions and their types
  fileTypes: {
    // Images
    jpg: 'image',
    jpeg: 'image',
    png: 'image',
    gif: 'image',
    bmp: 'image',
    tiff: 'image',
    svg: 'image',
    heic: 'image',

    // Videos
    mp4: 'video',
    m4v: 'video',
    mov: 'video',
    avi: 'video',
    wmv: 'video',
    mkv: 'video',
    flv: 'video',

    // Documents
    pdf: 'pdf',
    doc: 'doc',
    docx: 'doc',
    xls: 'xls',
    xlsx: 'xls',
    txt: 'txt',
    zip: 'zip',
    rar: 'zip',
    tar: 'zip',
    msg: 'msg',

    // Audio
    mp3: 'audio',
    wav: 'audio',
    aac: 'audio',
    m4a: 'audio',
    ogg: 'audio',
  },

  materialIconForFileType: {
    image: 'image',
    video: 'videocam',
    pdf: 'picture_as_pdf',
    doc: 'description',
    xls: 'description',
    txt: 'description',
    zip: 'folder_zip',
    audio: 'music_note',
    other: 'insert_drive_file',
  },

  menuAccessLevels: [
    {
      id: 1,
      label: 'Admin',
      value: 'admin',
    },
    {
      id: 2,
      label: 'Editor',
      value: 'editor',
    },
    {
      id: 3,
      label: 'Viewer',
      value: 'viewer',
    },
    // {
    //   id: 4,
    //   label: 'Submenu Viewer',
    //   value: 'submenuViewer'
    // }
  ],

  intercomApiBase: 'https://api-iam.intercom.io',
  intercomAppId: 'k24410lm',

  driverTypes: [
    {
      id: 1,
      label: 'Employee',
      value: 'employee',
    },
    {
      id: 2,
      label: 'Contractor',
      value: 'contractor',
    },
    {
      id: 3,
      label: 'Owner',
      value: 'owner',
    },
    {
      id: 4,
      label: 'Temp',
      value: 'temp',
    },
    {
      id: 5,
      label: 'Lowboy',
      value: 'lowboy',
    },
    {
      id: 6,
      label: 'End Dump',
      value: 'end_dump',
    },
    {
      id: 7,
      label: 'Dump Truck',
      value: 'dump_truck',
    },
    {
      id: 8,
      label: 'Grinding',
      value: 'grinding',
    },
    {
      id: 9,
      label: 'Pneumatic',
      value: 'pneumatic',
    },
    {
      id: 10,
      label: 'Asphalt',
      value: 'asphalt',
    },
    {
      id: 11,
      label: 'Concrete',
      value: 'concrete',
    },
    {
      id: 12,
      label: 'Mechanic',
      value: 'mechanic',
    },
    {
      id: 13,
      label: 'CDL',
      value: 'cdl',
    },
    {
      id: 14,
      label: 'CMV',
      value: 'cmv',
    },
    {
      id: 15,
      label: 'Non-CMV',
      value: 'nonCmv',
    },
    {
      id: 16,
      label: 'Other',
      value: 'other',
    },
  ],

  // Company Ids which have access to the Invoice Record Popup
  companiesWithInvoiceRecordPopupAccess: [36, 85],
  // Field & Submenu Ids to show data in the Invoice Record Popup
  invoiceRecordPopup: [
    {
      id: 1, // Used to identify the record in frontend (Should be unique. eg. 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ...)
      companyId: 36, // your company id
      fieldId: 201, // your sales orders submenu's record link field id (inside orders submenu)
      submenuId: 25, // your sales orders submenu's id
      priceFieldId: 185, // your inventory summary submenu's price field id
      // Warehouse options
      warehouseOptions: [
        // - id (Should be unique. eg. 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ...),
        // - label is the name of the option,
        // - value is the value of the option (i.e. the value that will be sent to the BE)
        { id: 1, label: 'Home', value: 117 },
        { id: 2, label: '15757', value: 119 },
      ],
    },
    {
      id: 2, // Used to identify the record in frontend (Should be unique. eg. 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ...)
      companyId: 85, // your company id
      fieldId: 625, // your sales orders submenu's record link field id (inside orders submenu)
      submenuId: 87, // your sales orders submenu's id
      priceFieldId: 572, // your inventory summary submenu's price field id
      // Warehouse options
      warehouseOptions: [
        { id: 1, label: 'Home', value: 319 },
        { id: 2, label: '15757', value: 321 },
      ],
    },
    // ........
  ],

  trailerHookOptions: [
    { label: 'Hook Loaded', value: 'loaded' },
    { label: 'Hook Empty', value: 'empty' },
  ],
  trailerDropOptions: [
    { label: 'Drop Loaded', value: 'loaded' },
    { label: 'Drop Empty', value: 'empty' },
  ],
  // Chart Colors
  chartColors: [
    '#64B5F6',
    '#4DD0E1',
    '#AED581',
    '#FFF176',
    '#FFB74D',
    '#E57373',
    '#A1887F',
    '#90A4AE',
    '#F06292',
    '#4FC3F7',
    '#81C784',
    '#BA68C8',
    '#FF8A65',
    '#DCE775',
    '#FFCDD2',
    '#BBDEFB',
    '#B2EBF2',
    '#DCEDC8',
    '#FFF9C4',
    '#FFE0B2',
    '#D7CCC8',
    '#CFD8DC',
    '#F8BBD0',
    '#B3E5FC',
    '#C8E6C9',
    '#E1BEE7',
    '#FFCCBC',
    '#00B3E6',
    '#FFB399',
    '#99FF99',
    '#FFFF99',
    '#E6B333',
    '#3366E6',
    '#999966',
    '#B34D4D',
    '#ff0000',
    '#ff8000',
    '#ffff00',
    '#80ff00',
    '#FF6633',
    '#FF33FF',
    '#00ff00',
    '#00ff80',
    '#00ffff',
    '#0080ff',
    '#0000ff',
    '#8000ff',
    '#ff00ff',
    '#ff0080',
    '#ff4d4d',
    '#ff994d',
    '#ffff4d',
    '#bfff4d',
    '#4dff4d',
    '#4dffb3',
    '#4dffff',
    '#4db3ff',
    '#4d4dff',
    '#b34dff',
    '#ff4dff',
    '#ff4db3',
    '#ff8080',
    '#ffb380',
    '#ffff80',
    '#dfff80',
    '#80ff80',
    '#80ffd4',
    '#80ffff',
    '#80d4ff',
    '#8080ff',
    '#d480ff',
    '#ff80ff',
    '#ff80d4',
    '#ff9999',
    '#ffc299',
    '#e5ff99',
    '#99ffe5',
    '#99ffff',
    '#99e5ff',
    '#9999ff',
    '#e599ff',
    '#ff99ff',
    '#ff99e5',
    '#ffb3b3',
    '#ffd9b3',
    '#ffffb3',
    '#f2ffb3',
    '#b3ffb3',
    '#b3fff2',
    '#b3ffff',
    '#b3f2ff',
    '#b3b3ff',
    '#f2b3ff',
    '#ffb3ff',
    '#ffb3f2',
    '#ffcccc',
    '#ffe5cc',
    '#ffffcc',
    '#f9ffcc',
    '#ccffcc',
    '#ccfff9',
    '#ccffff',
    '#ccf9ff',
    '#ccccff',
    '#f9ccff',
    '#ffccff',
    '#ffcce5',
    '#ffe6e6',
    '#fff2e6',
    '#ffffe6',
    '#fcffe6',
    '#e6ffe6',
    '#e6fffc',
    '#e6ffff',
    '#e6fcff',
    '#e6e6ff',
    '#fce6ff',
    '#ffe6ff',
    '#ffe6fc',
    '#ffebeb',
    '#fff5eb',
    '#ffffeb',
    '#fefeeb',
    '#ebffeb',
    '#ebfeff',
    '#ebebff',
    '#ebefff',
    '#ebefff',
    '#fdebeb',
    '#ffebff',
  ],
  // To be used in freight details and saved equipments
  weightOptions: [
    { label: 'lbs', value: 'lbs' },
    { label: 'tons', value: 'tons' },
    { label: 'kg', value: 'kg' },
  ],
  qtyOptions: [
    { label: 'pallets', value: 'pallets' },
    { label: 'crates', value: 'crates' },
    { label: 'hours', value: 'hours' },
    { label: 'days', value: 'days' },
    { label: 'miles', value: 'miles' },
    { label: 'yards', value: 'yards' },
    { label: 'feet', value: 'feet' },
    { label: 'cases', value: 'cases' },
    { label: 'gallons', value: 'gallons' },
  ],

  loadPictureMaxWidthHeight: '310px',

  safetyModule: {
    status: [
      { id: 1, label: 'Open', value: 'open' },
      { id: 2, label: 'Closed', value: 'closed' },
      { id: 3, label: 'Denied', value: 'denied' },
    ],
    yesOrNo: [
      { id: 1, label: 'Yes', value: 'yes' },
      { id: 2, label: 'No', value: 'no' },
    ],
    yesOrNoOrUnknown: [
      { id: 1, label: 'Yes', value: 'yes' },
      { id: 2, label: 'No', value: 'no' },
      { id: 3, label: 'Unknown', value: 'unknown' },
    ],
    involvedTypes: [
      { id: 1, label: 'Employee', value: 'employee' },
      { id: 2, label: 'Carrier', value: 'carrier' },
      { id: 3, label: 'Vendor', value: 'vendor' },
      { id: 4, label: 'Unknown', value: 'unknown' },
      {
        id: 5,
        label: 'Independent Contractor',
        value: 'independentContractor',
      },
      { id: 6, label: 'Owner Operator', value: 'ownerOperator' },
    ],
    involvedPersonTypes: [
      { id: 1, label: 'Driver', value: 'driver' },
      { id: 2, label: 'Yard Hostler', value: 'yardHostler' },
      { id: 3, label: 'Carrier', value: 'carrier' },
      { id: 4, label: 'Vendor', value: 'vendor' },
      { id: 5, label: 'Mechanic', value: 'mechanic' },
      { id: 6, label: 'Unknown', value: 'unknown' },
      {
        id: 7,
        label: 'Independent Contractor',
        value: 'independentContractor',
      },
      { id: 8, label: 'Owner Operator', value: 'ownerOperator' },
    ],
    locationTypes: [
      { id: 1, label: 'Highway', value: 'hwy' },
      { id: 2, label: 'Store', value: 'store' },
      { id: 3, label: 'Supplier', value: 'supplier' },
      { id: 4, label: 'Vendor', value: 'vendor' },
      { id: 5, label: 'Yard', value: 'yard' },
      { id: 6, label: 'Shop', value: 'shop' },
      { id: 7, label: 'Other', value: 'other' },
    ],
    incidentTypes: [
      { id: 1, label: 'Collision', value: 'collision' },
      { id: 2, label: 'Fuel Spill', value: 'fuelSpill' },
      { id: 3, label: 'Product Damage', value: 'productDamage' },
      { id: 4, label: 'Property Damage', value: 'propertyDamage' },
      { id: 5, label: 'Bodily Injury', value: 'bodilyInjury' },
      { id: 6, label: 'Theft', value: 'theft' },
      { id: 7, label: 'Trailer Damage', value: 'trailerDamage' },
      { id: 8, label: 'Truck Damage', value: 'truckDamage' },
      { id: 9, label: 'Near Miss', value: 'nearMiss' },
      { id: 10, label: 'Unreported', value: 'unreported' },
      { id: 99, label: 'Other', value: 'other' },
    ],
    contactType: [
      { id: 1, label: 'Adjuster', value: 'adjuster' },
      { id: 2, label: 'Appraiser', value: 'appraiser' },
      { id: 3, label: 'Attorney', value: 'attorney' },
      { id: 4, label: 'Third Party Administrator', value: 'tpa' },
      { id: 5, label: 'Carrier', value: 'carrier' },
      { id: 6, label: 'Property Manager', value: 'propertyManager' },
      { id: 7, label: 'Rental Company', value: 'rentalCompany' },
      { id: 8, label: 'Store', value: 'store' },
      { id: 9, label: 'Vehicle Owner', value: 'vehicleOwner' },
      { id: 10, label: 'Misc.', value: 'misc' },
      { id: 11, label: 'Insurance Agent', value: 'insuranceAgent' },
    ],
    fileLabelOptions: [
      { id: 1, label: 'NCIC Report', value: 'ncicReport' },
      { id: 2, label: 'Jotform', value: 'jotform' },
      { id: 3, label: 'Manifest', value: 'manifest' },
      { id: 4, label: 'Video', value: 'video' },
      { id: 5, label: 'Driver Statement', value: 'driverStatement' },
      { id: 6, label: 'Scene Diagram', value: 'sceneDiagram' },
      { id: 7, label: 'Reefer Download', value: 'reeferDownload' },
      { id: 8, label: 'Email', value: 'email' },
      { id: 9, label: 'Picture', value: 'picture' },
      { id: 10, label: 'Check', value: 'check' },
      { id: 11, label: 'Claim', value: 'claim' },
      { id: 12, label: 'Charge Back', value: 'chargeBack' },
      { id: 13, label: 'Incident Report', value: 'incidentReport' },
      { id: 14, label: 'Release of Claims', value: 'releaseOfClaims' },
      { id: 15, label: 'License', value: 'license' },
      { id: 16, label: 'Insurance', value: 'insurance' },
      { id: 17, label: 'Internal', value: 'internal' },
      { id: 18, label: 'Customer', value: 'customer' },
      { id: 19, label: 'BOL', value: 'bol' },
      { id: 20, label: 'Client Charge Back', value: 'clientChargeBack' },
      { id: 21, label: 'Misc.', value: 'misc' },
      { id: 22, label: 'Product Loss Detail', value: 'productLossDetail' },
    ],
    tableDefaultCols: [
      {
        id: 1,
        colId: 'tag',
        field: 'tag',
        key: 'tags',
        label: 'Tag',
        isSortable: false,
        filter: {
          type: 'dropdown',
          key: 'tagId',
          options: 'allTags',
          placeholder: 'Tag',
          optionLabel: 'business_name',
          optionValue: 'tag_id',
        },
      },
      {
        id: 2,
        colId: 'incidentDate',
        field: 'incidentDate',
        key: 'incidentDate',
        label: 'Incident Date',
        style: { minWidth: '130px' },
        isSortable: true,
        filter: {
          type: 'dateRange',
          key: 'incidentDate',
        },
      },
      {
        id: 3,
        colId: 'incidentTime',
        field: 'incidentTime',
        key: 'incidentTime',
        label: 'Incident Time',
        style: { minWidth: '120px' },
        isSortable: false,
        filter: {},
      },
      {
        id: 4,
        colId: 'status',
        field: 'status',
        key: 'status',
        label: 'Status',
        isSortable: true,
        filter: {
          type: 'dropdown',
          key: 'status',
          options: 'status',
          placeholder: 'Status',
          optionLabel: 'label',
          optionValue: 'value',
        },
      },
      {
        id: 5,
        colId: 'closedDate',
        field: 'closedDate',
        key: 'closedDate',
        label: 'Closed Date',
        style: { minWidth: '120px' },
        isSortable: true,
        filter: {
          type: 'dateRange',
          key: 'closedDate',
        },
      },
      {
        id: 6,
        colId: 'assignee',
        field: 'assigneeUserName',
        key: 'assigneeUserName',
        label: 'Assignee',
        style: { minWidth: '120px' },
        isSortable: false,
        filter: {
          type: 'text',
          key: 'assigneeUserName',
        },
      },
      {
        id: 7,
        colId: 'followUpDate',
        field: 'followUpDate',
        key: 'followUpDate',
        label: 'Follow Up Date',
        style: { minWidth: '120px' },
        isSortable: false,
        filter: {
          type: 'date',
          key: 'followUpDate',
        },
      },
      {
        id: 8,
        colId: 'notes',
        field: 'notes',
        key: 'notes',
        label: 'Notes',
        style: { minWidth: '120px' },
        isSortable: false,
        filter: {
          type: 'text',
          key: 'notes',
        },
      },
      {
        id: 9,
        colId: 'incidentClaimNumber',
        field: 'incidentClaimNumber',
        key: 'incidentClaimNumber',
        label: 'Incident Claim Number',
        style: { minWidth: '120px' },
        isSortable: false,
        filter: {
          type: 'text',
          key: 'incidentClaimNumber',
        },
      },
      {
        id: 10,
        colId: 'thirdPartyIncidentClaimNumber',
        field: 'thirdPartyIncidentClaimNumber',
        key: 'thirdPartyIncidentClaimNumber',
        label: 'Third Party Incident Claim Number',
        style: { minWidth: '120px' },
        isSortable: false,
        filter: {
          type: 'text',
          key: 'thirdPartyIncidentClaimNumber',
        },
      },
      {
        id: 11,
        colId: 'ncicNumber',
        field: 'ncicNumber',
        key: 'ncicNumber',
        label: 'Ncic Number',
        style: { minWidth: '120px' },
        isSortable: false,
        filter: {
          type: 'text',
          key: 'ncicNumber',
        },
      },
      {
        id: 12,
        colId: 'ncicReport',
        field: 'ncicReport',
        key: 'ncicReport',
        label: 'Ncic Report',
        style: { minWidth: '120px' },
        isSortable: false,
        filter: {
          type: 'dropdown',
          key: 'ncicReport',
          options: 'yesOrNo',
          placeholder: 'Yes/No',
          optionLabel: 'label',
          optionValue: 'value',
        },
      },
      {
        id: 13,
        colId: 'savedAddressAffected',
        field: 'savedAddressAffected',
        key: 'savedAddressAffected',
        label: 'Saved Address Affected',
        isSortable: false,
        filter: {
          type: 'dropdown',
          key: 'savedAddressAffected',
          options: 'yesOrNo',
          placeholder: 'Yes/No',
          optionLabel: 'label',
          optionValue: 'value',
        },
      },
      {
        id: 14,
        colId: 'chargeBack',
        field: 'chargeBack',
        key: 'chargeBack',
        label: 'Charge Back',
        isSortable: false,
        filter: {
          type: 'dropdown',
          key: 'chargeBack',
          options: 'yesOrNo',
          placeholder: 'Yes/No',
          optionLabel: 'label',
          optionValue: 'value',
        },
      },
      {
        id: 15,
        colId: 'chargeBackAmount',
        field: 'chargeBackAmount',
        key: 'chargeBackAmount',
        label: 'Charge Back Amount',
        style: { minWidth: '120px' },
        isSortable: true,
        filter: {
          type: 'number',
          key: 'chargeBackAmount',
        },
      },
      {
        id: 16,
        colId: 'estimates',
        field: 'estimates',
        key: 'estimates',
        label: 'Estimates Needed',
        isSortable: false,
        filter: {
          type: 'dropdown',
          key: 'estimates',
          options: 'yesOrNo',
          placeholder: 'Yes/No',
          optionLabel: 'label',
          optionValue: 'value',
        },
      },
      {
        id: 17,
        colId: 'estimatesReceived',
        field: 'estimatesReceived',
        key: 'estimatesReceived',
        label: 'Estimates Received',
        isSortable: false,
        filter: {
          type: 'dropdown',
          key: 'estimatesReceived',
          options: 'yesOrNo',
          placeholder: 'Yes/No',
          optionLabel: 'label',
          optionValue: 'value',
        },
      },
      {
        id: 18,
        colId: 'costIncurred',
        field: 'costIncurred',
        key: 'costIncurred',
        label: 'Cost Incurred',
        isSortable: false,
        filter: {
          type: 'dropdown',
          key: 'costIncurred',
          options: 'yesOrNo',
          placeholder: 'Yes/No',
          optionLabel: 'label',
          optionValue: 'value',
        },
      },
      {
        id: 19,
        colId: 'costAmount',
        field: 'costAmount',
        key: 'costAmount',
        label: 'Cost Amount',
        style: { minWidth: '120px' },
        isSortable: true,
        filter: {
          type: 'number',
          key: 'costAmount',
        },
      },
      {
        id: 20,
        colId: 'insuranceCompanyName',
        field: 'dealWithInsuranceCompanyName',
        key: 'dealWithInsuranceCompanyName',
        label: 'Insurance Company Name',
        style: { minWidth: '120px' },
        isSortable: false,
        filter: {
          type: 'text',
          key: 'insuranceCompanyName',
        },
      },
      {
        id: 21,
        colId: 'involvedType',
        field: 'involvedType',
        key: 'involvedType',
        label: 'Involved Type',
        isSortable: false,
        filter: {
          type: 'dropdown',
          key: 'involvedType',
          options: 'involvedTypes',
          placeholder: 'Involved Type',
          optionLabel: 'label',
          optionValue: 'value',
        },
      },
      {
        id: 22,
        colId: 'involvedPersonType',
        field: 'involvedPersonType',
        key: 'involvedPersonType',
        label: 'Person Type',
        isSortable: false,
        filter: {
          type: 'dropdown',
          key: 'involvedPersonType',
          options: 'involvedPersonTypes',
          placeholder: 'Involved Person Type',
          optionLabel: 'label',
          optionValue: 'value',
        },
      },
      {
        id: 23,
        colId: 'involvedPersonName',
        field: 'involvedPersonName',
        key: 'involvedPersonName',
        label: 'Person Name',
        style: { minWidth: '120px' },
        isSortable: false,
        filter: {
          type: 'text',
          key: 'involvedPersonName',
        },
      },
      {
        id: 24,
        colId: 'involvedThirdParty',
        field: 'involvedThirdPartyName',
        key: 'involvedThirdPartyName',
        label: 'Company Involved',
        style: { minWidth: '120px' },
        isSortable: false,
        filter: {
          type: 'text',
          key: 'involvedThirdPartyName',
        },
      },
      {
        id: 25,
        colId: 'correctiveActionApplied',
        field: 'correctiveActionApplied',
        key: 'correctiveActionApplied',
        label: 'Corrective Action Applied',
        isSortable: false,
        filter: {
          type: 'dropdown',
          key: 'correctiveActionApplied',
          options: 'yesOrNo',
          placeholder: 'Yes/No',
          optionLabel: 'label',
          optionValue: 'value',
        },
      },
      {
        id: 26,
        colId: 'dotRecordable',
        field: 'dotRecordable',
        key: 'dotRecordable',
        label: 'DOT Recordable',
        isSortable: false,
        filter: {
          type: 'dropdown',
          key: 'dotRecordable',
          options: 'yesOrNo',
          placeholder: 'Yes/No',
          optionLabel: 'label',
          optionValue: 'value',
        },
      },
      {
        id: 27,
        colId: 'preventable',
        field: 'preventable',
        key: 'preventable',
        label: 'Preventable',
        isSortable: false,
        filter: {
          type: 'dropdown',
          key: 'preventable',
          options: 'yesOrNoOrUnknown',
          placeholder: 'Yes/No/Unknown',
          optionLabel: 'label',
          optionValue: 'value',
        },
      },
      {
        id: 28,
        colId: 'atFault',
        field: 'atFault',
        key: 'atFault',
        label: 'At Fault',
        isSortable: false,
        filter: {
          type: 'dropdown',
          key: 'atFault',
          options: 'yesOrNoOrUnknown',
          placeholder: 'Yes/No/Unknown',
          optionLabel: 'label',
          optionValue: 'value',
        },
      },
      {
        id: 29,
        colId: 'truck',
        field: 'truckNumber',
        key: 'truckNumber',
        label: 'Truck',
        style: { minWidth: '120px' },
        isSortable: false,
        filter: {
          type: 'text',
          key: 'truckNumber',
        },
      },
      {
        id: 30,
        colId: 'trailer',
        field: 'trailerNumber',
        key: 'trailerNumber',
        label: 'Trailer',
        style: { minWidth: '120px' },
        isSortable: false,
        filter: {
          type: 'text',
          key: 'trailerNumber',
        },
      },
      {
        id: 31,
        colId: 'locationType',
        field: 'locationType',
        key: 'locationType',
        label: 'Location Type',
        isSortable: false,
        filter: {
          type: 'dropdown',
          key: 'locationType',
          options: 'locationTypes',
          placeholder: 'Location Type',
          optionLabel: 'label',
          optionValue: 'value',
        },
      },
      {
        id: 32,
        colId: 'savedAddress',
        field: 'address',
        key: 'address',
        label: 'Address',
        style: { minWidth: '120px' },
        isSortable: false,
        filter: {
          type: 'text',
          key: 'address',
        },
      },
      {
        id: 33,
        colId: 'reported',
        field: 'reported',
        key: 'reported',
        label: 'Reported',
        isSortable: false,
        filter: {
          type: 'dropdown',
          key: 'reported',
          options: 'yesOrNo',
          placeholder: 'Reported',
          optionLabel: 'label',
          optionValue: 'value',
        },
      },
      {
        id: 34,
        colId: 'incidentType',
        field: 'incidentType',
        key: 'incidentType',
        label: 'Incident Type',
        isSortable: false,
        filter: {
          type: 'dropdown',
          key: 'incidentType',
          options: 'incidentTypes',
          placeholder: 'Incident Type',
          optionLabel: 'label',
          optionValue: 'value',
        },
      },
      {
        id: 35,
        colId: 'jotformReport',
        field: 'jotformReport',
        key: 'jotformReport',
        label: 'Jotform Report',
        isSortable: false,
        filter: {
          type: 'dropdown',
          key: 'jotformReport',
          options: 'yesOrNo',
          placeholder: 'Yes/No',
          optionLabel: 'label',
          optionValue: 'value',
        },
      },
      {
        id: 36,
        colId: 'description',
        field: 'description',
        key: 'description',
        label: 'Description',
        style: { minWidth: '120px' },
        isSortable: false,
        filter: {
          type: 'text',
          key: 'description',
        },
      },
    ],
    formLabels: {
      tag: 'Tag',
      incidentDate: 'Incident Date',
      incidentTime: 'Incident Time',
      status: 'Status',
      closedDate: 'Closed Date',
      assigneeUserId: 'Assignee',
      followUpDate: 'Follow Up Date',
      notes: 'Notes',
      incidentClaimNumber: 'Incident Claim Number',
      thirdPartyIncidentClaimNumber: 'Third Party Claim Number',
      ncicNumber: 'Ncic Number',
      savedAddressAffected: 'Saved Address Affected',
      chargeBack: 'Charge Back',
      chargeBackAmount: 'Charge Back Amount',
      estimates: 'Estimates Needed',
      estimatesReceived: 'Estimates Received',
      costIncurred: 'Cost Incurred',
      costAmount: 'Cost Amount',
      dealWithInsuranceCompanyName: 'Insurance Company',
      involvedType: 'Involved Type',
      involvedPersonName: 'Person Name',
      involvedThirdPartyName: 'Company Involved',
      involvedPersonType: 'Person Type',
      correctiveActionApplied: 'Corrective Action Applied',
      dotRecordable: 'DOT Recordable',
      preventable: 'Preventable',
      atFault: 'At Fault',
      truckNumber: 'Truck',
      trailerNumber: 'Trailer',
      locationType: 'Location Type',
      address: 'Address',
      reported: 'Reported',
      incidentType: 'Incident Type',
      description: 'Description',
    },
    customFormLabels: {
      tag: 'Site',
      savedAddressAffected: 'Store Affected',
      address: 'Store #',
    },
  },

  loadLogStatuses: {
    adminDispatcherAssignVehicleToLoad: '',
    driverAssignVehicleToLoad: '',
    driverArriveAtShipper: 'Arrived at shipper',
    driverLoadedAtShipper: 'Loaded at shipper',
    driverArriveAtReceiver: 'Arrived at receiver',
    driverUnloadedAtReceiver: 'Unloaded at receiver',
    driverHandedOver: 'Handed over',
    createLoad: 'Created load',
    generateInvoice: 'Generated Invoice',
    requestPayment: 'Requested Payment',
    loadPaid: 'Marked load as paid',
    dropEmptyTrailer: 'Dropped empty trailer',
    dropLoadedTrailer: 'Dropped loaded trailer',
    hookEmptyTrailer: 'Hooked empty trailer',
    hookLoadedTrailer: 'Hooked loaded trailer',
  },

  socketIoEvents: {
    joinRoom: 'joinRoom',
    newMessages: 'newMessages',
  },

  eventBuses: {
    loadChanged: 'loadChanged',
  },

  marketing: {
    activitiesCollection: {
      phone: 'Phone',
      name: 'Deal Name',
      assignees: 'Assignees',
      amount: 'Amount',
      stage: 'Stage',
      customer: 'Customer',
      estimatedCloseDate: 'Estimated Close Date',
      task: 'Task',
      contact: 'Contact',
      contacts: 'Contacts',
      notes: 'Note',
      probability: 'Probability',
      add: 'added',
      change: 'changed',
      remove: 'removed',
      create: 'created',
    },
  },

  googleAnalyticsMeasurementId:
    process.env.NODE_ENV === 'production'
      ? 'G-CF1XYE8HJQ' // production
      : 'G-3RCSM8Z6X0', // development
};
