export default [
  { label: 'Accounting', value: 'accounting' },
  { label: 'Agriculture', value: 'agriculture' },
  { label: 'Airlines/Aviation', value: 'airlines/aviation' },
  {
    label: 'Alternative Dispute Resolution',
    value: 'alternative dispute resolution',
  },
  { label: 'Alternative Medicine', value: 'alternative medicine' },
  { label: 'Animation', value: 'animation' },
  { label: 'Apparel & Fashion', value: 'apparel & fashion' },
  { label: 'Architecture & Planning', value: 'architecture & planning' },
  { label: 'Arts & Crafts', value: 'arts & crafts' },
  { label: 'Automotive', value: 'automotive' },
  { label: 'Aviation & Aerospace', value: 'aviation & aerospace' },
  { label: 'Banking', value: 'banking' },
  { label: 'Biotechnology', value: 'biotechnology' },
  { label: 'Broadcast Media', value: 'broadcast media' },
  { label: 'Building Materials', value: 'building materials' },
  {
    label: 'Business Supplies & Equipment',
    value: 'business supplies & equipment',
  },
  { label: 'Capital Markets', value: 'capital markets' },
  { label: 'Chemicals', value: 'chemicals' },
  {
    label: 'Civic & Social Organization',
    value: 'civic & social organization',
  },
  { label: 'Civil Engineering', value: 'civil engineering' },
  { label: 'Commercial Real Estate', value: 'commercial real estate' },
  {
    label: 'Computer & Network Security',
    value: 'computer & network security',
  },
  { label: 'Computer Games', value: 'computer games' },
  { label: 'Computer Hardware', value: 'computer hardware' },
  { label: 'Computer Networking', value: 'computer networking' },
  { label: 'Computer Software', value: 'computer software' },
  { label: 'Construction', value: 'construction' },
  { label: 'Consumer Electronics', value: 'consumer electronics' },
  { label: 'Consumer Goods', value: 'consumer goods' },
  { label: 'Consumer Services', value: 'consumer services' },
  { label: 'Cosmetics', value: 'cosmetics' },
  { label: 'Dairy', value: 'dairy' },
  { label: 'Defense & Space', value: 'defense & space' },
  { label: 'Design', value: 'design' },
  { label: 'E-Learning', value: 'e-learning' },
  { label: 'Education Management', value: 'education management' },
  {
    label: 'Electrical/Electronic Manufacturing',
    value: 'electrical/electronic manufacturing',
  },
  { label: 'Entertainment', value: 'entertainment' },
  { label: 'Environmental Services', value: 'environmental services' },
  { label: 'Events Services', value: 'events services' },
  { label: 'Executive Office', value: 'executive office' },
  { label: 'Facilities Services', value: 'facilities services' },
  { label: 'Farming', value: 'farming' },
  { label: 'Financial Services', value: 'financial services' },
  { label: 'Fine Art', value: 'fine art' },
  { label: 'Fishery', value: 'fishery' },
  { label: 'Food & Beverages', value: 'food & beverages' },
  { label: 'Food Production', value: 'food production' },
  { label: 'Fund-Raising', value: 'fund-raising' },
  { label: 'Furniture', value: 'furniture' },
  { label: 'Gambling & Casinos', value: 'gambling & casinos' },
  { label: 'Glass, Ceramics & Concrete', value: 'glass, ceramics & concrete' },
  { label: 'Government Administration', value: 'government administration' },
  { label: 'Government Relations', value: 'government relations' },
  { label: 'Graphic Design', value: 'graphic design' },
  { label: 'Health, Wellness & Fitness', value: 'health, wellness & fitness' },
  { label: 'Higher Education', value: 'higher education' },
  { label: 'Hospital & Health Care', value: 'hospital & health care' },
  { label: 'Hospitality', value: 'hospitality' },
  { label: 'Human Resources', value: 'human resources' },
  { label: 'Import & Export', value: 'import & export' },
  {
    label: 'Individual & Family Services',
    value: 'individual & family services',
  },
  { label: 'Industrial Automation', value: 'industrial automation' },
  { label: 'Information Services', value: 'information services' },
  {
    label: 'Information Technology & Services',
    value: 'information technology & services',
  },
  { label: 'Insurance', value: 'insurance' },
  { label: 'International Affairs', value: 'international affairs' },
  {
    label: 'International Trade & Development',
    value: 'international trade & development',
  },
  { label: 'Internet', value: 'internet' },
  { label: 'Investment Banking', value: 'investment banking' },
  { label: 'Investment Management', value: 'investment management' },
  { label: 'Judiciary', value: 'judiciary' },
  { label: 'Law Enforcement', value: 'law enforcement' },
  { label: 'Law Practice', value: 'law practice' },
  { label: 'Legal Services', value: 'legal services' },
  { label: 'Legislative Office', value: 'legislative office' },
  { label: 'Leisure, Travel & Tourism', value: 'leisure, travel & tourism' },
  { label: 'Libraries', value: 'libraries' },
  { label: 'Logistics & Supply Chain', value: 'logistics & supply chain' },
  { label: 'Luxury Goods & Jewelry', value: 'luxury goods & jewelry' },
  { label: 'Machinery', value: 'machinery' },
  { label: 'Management Consulting', value: 'management consulting' },
  { label: 'Maritime', value: 'maritime' },
  { label: 'Market Research', value: 'market research' },
  { label: 'Marketing & Advertising', value: 'marketing & advertising' },
  {
    label: 'Mechanical Or Industrial Engineering',
    value: 'mechanical or industrial engineering',
  },
  { label: 'Media Production', value: 'media production' },
  { label: 'Medical Devices', value: 'medical devices' },
  { label: 'Medical Practice', value: 'medical practice' },
  { label: 'Mental Health Care', value: 'mental health care' },
  { label: 'Military', value: 'military' },
  { label: 'Mining & Metals', value: 'mining & metals' },
  { label: 'Motion Pictures & Film', value: 'motion pictures & film' },
  { label: 'Museums & Institutions', value: 'museums & institutions' },
  { label: 'Music', value: 'music' },
  { label: 'Nanotechnology', value: 'nanotechnology' },
  { label: 'Newspapers', value: 'newspapers' },
  {
    label: 'Nonprofit Organization Management',
    value: 'nonprofit organization management',
  },
  { label: 'Oil & Energy', value: 'oil & energy' },
  { label: 'Online Media', value: 'online media' },
  { label: 'Outsourcing/Offshoring', value: 'outsourcing/offshoring' },
  { label: 'Package/Freight Delivery', value: 'package/freight delivery' },
  { label: 'Packaging & Containers', value: 'packaging & containers' },
  { label: 'Paper & Forest Products', value: 'paper & forest products' },
  { label: 'Performing Arts', value: 'performing arts' },
  { label: 'Pharmaceuticals', value: 'pharmaceuticals' },
  { label: 'Philanthropy', value: 'philanthropy' },
  { label: 'Photography', value: 'photography' },
  { label: 'Plastics', value: 'plastics' },
  { label: 'Political Organization', value: 'political organization' },
  {
    label: 'Primary/Secondary Education',
    value: 'primary/secondary education',
  },
  { label: 'Printing', value: 'printing' },
  {
    label: 'Professional Training & Coaching',
    value: 'professional training & coaching',
  },
  { label: 'Program Development', value: 'program development' },
  { label: 'Public Policy', value: 'public policy' },
  {
    label: 'Public Relations & Communications',
    value: 'public relations & communications',
  },
  { label: 'Public Safety', value: 'public safety' },
  { label: 'Publishing', value: 'publishing' },
  { label: 'Railroad Manufacture', value: 'railroad manufacture' },
  { label: 'Ranching', value: 'ranching' },
  { label: 'Real Estate', value: 'real estate' },
  {
    label: 'Recreational Facilities & Services',
    value: 'recreational facilities & services',
  },
  { label: 'Religious Institutions', value: 'religious institutions' },
  { label: 'Renewables & Environment', value: 'renewables & environment' },
  { label: 'Research', value: 'research' },
  { label: 'Restaurants', value: 'restaurants' },
  { label: 'Retail', value: 'retail' },
  { label: 'Security & Investigations', value: 'security & investigations' },
  { label: 'Semiconductors', value: 'semiconductors' },
  { label: 'Shipbuilding', value: 'shipbuilding' },
  { label: 'Sporting Goods', value: 'sporting goods' },
  { label: 'Sports', value: 'sports' },
  { label: 'Staffing & Recruiting', value: 'staffing & recruiting' },
  { label: 'Supermarkets', value: 'supermarkets' },
  { label: 'Telecommunications', value: 'telecommunications' },
  { label: 'Textiles', value: 'textiles' },
  { label: 'Think Tanks', value: 'think tanks' },
  { label: 'Tobacco', value: 'tobacco' },
  { label: 'Translation & Localization', value: 'translation & localization' },
  {
    label: 'Transportation/Trucking/Railroad',
    value: 'transportation/trucking/railroad',
  },
  { label: 'Utilities', value: 'utilities' },
  {
    label: 'Venture Capital & Private Equity',
    value: 'venture capital & private equity',
  },
  { label: 'Veterinary', value: 'veterinary' },
  { label: 'Warehousing', value: 'warehousing' },
  { label: 'Wholesale', value: 'wholesale' },
  { label: 'Wine & Spirits', value: 'wine & spirits' },
  { label: 'Wireless', value: 'wireless' },
  { label: 'Writing & Editing', value: 'writing & editing' },
];
