<?php

return [
  'type' => [
    1 => [
      'name' => 'Bank',
      'subTypes' => [
        1 => 'CashOnHand',
        2 => 'Checking',
        3 => 'MoneyMarket',
        4 => 'RentsHeldInTrust',
        5 => 'Savings',
        6 => 'TrustAccounts',
        7 => 'CashAndCashEquivalents',
        8 => 'OtherEarMarkedBankAccounts',
      ]
    ],
    2 => [
      'name' => 'Other Current Asset',
      'subTypes' => [
        9 => 'AllowanceForBadDebts',
        10 => 'DevelopmentCosts',
        11 => 'EmployeeCashAdvances',
        12 => 'OtherCurrentAssets',
        13 => 'Inventory',
        14 => 'Investment_MortgageRealEstateLoans',
        15 => 'Investment_Other',
        16 => 'Investment_TaxExemptSecurities',
        17 => 'Investment_USGovernmentObligations',
        18 => 'LoansToOfficers',
        19 => 'LoansToOthers',
        20 => 'LoansToStockholders',
        21 => 'PrepaidExpenses',
        22 => 'Retainage',
        23 => 'UndepositedFunds',
        24 => 'AssetsAvailableForSale',
        25 => 'BalWithGovtAuthorities',
        26 => 'CalledUpShareCapitalNotPaid',
        27 => 'ExpenditureAuthorisationsAndLettersOfCredit',
        28 => 'GlobalTaxDeferred',
        29 => 'GlobalTaxRefund',
        30 => 'InternalTransfers',
        31 => 'OtherConsumables',
        32 => 'ProvisionsCurrentAssets',
        33 => 'ShortTermInvestmentsInRelatedParties',
        34 => 'ShortTermLoansAndAdvancesToRelatedParties',
        35 => 'TradeAndOtherReceivables',
      ]
    ],
    3 => [
      'name' => 'Fixed Asset',
      'subTypes' => [
        36 => 'AccumulatedDepletion',
        37 => 'AccumulatedDepreciation',
        38 => 'DepletableAssets',
        39 => 'FixedAssetComputers',
        40 => 'FixedAssetCopiers',
        41 => 'FixedAssetFurniture',
        42 => 'FixedAssetPhone',
        43 => 'FixedAssetPhotoVideo',
        44 => 'FixedAssetSoftware',
        45 => 'FixedAssetOtherToolsEquipment',
        46 => 'FurnitureAndFixtures',
        47 => 'Land',
        48 => 'LeaseholdImprovements',
        49 => 'OtherFixedAssets',
        50 => 'AccumulatedAmortization',
        51 => 'Buildings',
        52 => 'IntangibleAssets',
        53 => 'MachineryAndEquipment',
        54 => 'Vehicles',
        55 => 'AssetsInCourseOfConstruction',
        56 => 'CapitalWip',
        57 => 'CumulativeDepreciationOnIntangibleAssets',
        58 => 'IntangibleAssetsUnderDevelopment',
        59 => 'LandAsset',
        60 => 'NonCurrentAssets',
        61 => 'ParticipatingInterests',
        62 => 'ProvisionsFixedAssets',
      ]
    ],
    4 => [
      'name' => 'Other Asset',
      'subTypes' => [
        63 => 'LeaseBuyout',
        64 => 'OtherLongTermAssets',
        65 => 'SecurityDeposits',
        66 => 'AccumulatedAmortizationOfOtherAssets',
        67 => 'Goodwill',
        68 => 'Licenses',
        69 => 'OrganizationalCosts',
        70 => 'AssetsHeldForSale',
        71 => 'AvailableForSaleFinancialAssets',
        72 => 'DeferredTax',
        73 => 'Investments',
        74 => 'LongTermInvestments',
        75 => 'LongTermLoansAndAdvancesToRelatedParties',
        76 => 'OtherIntangibleAssets',
        77 => 'OtherLongTermInvestments',
        78 => 'OtherLongTermLoansAndAdvances',
        79 => 'PrepaymentsAndAccruedIncome',
        80 => 'ProvisionsNonCurrentAssets',
      ]
    ],
    5 => [
      'name' => 'Accounts Receivable',
      'subTypes' => [
        81 => 'AccountsReceivable',
      ]
    ],
    6 => [
      'name' => 'Equity',
      'subTypes' => [
        82 => 'OpeningBalanceEquity',
        83 => 'PartnersEquity',
        84 => 'RetainedEarnings',
        85 => 'AccumulatedAdjustment',
        86 => 'OwnersEquity',
        87 => 'PaidInCapitalOrSurplus',
        88 => '​PartnerContributions',
        89 => 'PartnerDistributions',
        90 => 'PreferredStock',
        91 => 'CommonStock',
        92 => 'TreasuryStock',
        93 => 'EstimatedTaxes',
        94 => 'Healthcare',
        95 => 'PersonalIncome',
        96 => 'PersonalExpense',
        97 => 'AccumulatedOtherComprehensiveIncome',
        98 => 'CalledUpShareCapital',
        99 => 'CapitalReserves',
        100 => 'DividendDisbursed',
        101 => 'EquityInEarningsOfSubsiduaries',
        102 => 'InvestmentGrants',
        103 => 'MoneyReceivedAgainstShareWarrants',
        104 => 'OtherFreeReserves',
        105 => 'ShareApplicationMoneyPendingAllotment',
        106 => 'ShareCapital',
        107 => 'Funds',
      ]
    ],
    7 => [
      'name' => 'Expense',
      'subTypes' => [
        108 => 'AdvertisingPromotional',
        109 => 'BadDebts',
        110 => 'BankCharges',
        111 => 'CharitableContributions',
        112 => 'Communications', // This one exist but is not on their doc, weird. While CommissionsAndFees shows up twice. I think their doc is wrong.
        113 => 'Entertainment',
        114 => 'EntertainmentMeals',
        115 => 'EquipmentRental',
        116 => 'FinanceCosts',
        117 => 'GlobalTaxExpense',
        118 => 'Insurance',
        119 => 'InterestPaid',
        120 => 'LegalProfessionalFees',
        121 => 'OfficeExpenses',
        122 => 'OfficeGeneralAdministrativeExpenses',
        123 => 'OtherBusinessExpenses',
        124 => 'OtherMiscellaneousServiceCost',
        125 => 'PromotionalMeals',
        126 => 'RentOrLeaseOfBuildings',
        127 => 'RepairMaintenance',
        128 => 'ShippingFreightDelivery',
        129 => 'SuppliesMaterials',
        130 => 'Travel',
        131 => 'TravelMeals',
        132 => 'Utilities',
        133 => 'Auto',
        134 => 'CostOfLabor',
        135 => 'DuesSubscriptions',
        136 => 'PayrollExpenses',
        277 => 'PayrollTaxExpenses',
        278 => 'PayrollWageExpenses',
        137 => 'TaxesPaid',
        138 => 'UnappliedCashBillPaymentExpense',
        // 139 => 'Utilities', I think QBO website has a bug, so this shows up twice in their doc.
        140 => 'AmortizationExpense',
        141 => 'AppropriationsToDepreciation',
        142 => 'BorrowingCost',
        143 => 'CommissionsAndFees',
        144 => 'DistributionCosts',
        145 => 'ExternalServices',
        146 => 'ExtraordinaryCharges',
        147 => 'IncomeTaxExpense',
        148 => 'LossOnDiscontinuedOperationsNetOfTax',
        149 => 'ManagementCompensation',
        150 => 'OtherCurrentOperatingCharges',
        151 => 'OtherExternalServices',
        152 => 'OtherRentalCosts',
        153 => 'OtherSellingExpenses',
        154 => 'ProjectStudiesSurveysAssessments',
        155 => 'PurchasesRebates',
        156 => 'ShippingAndDeliveryExpense',
        157 => 'StaffCosts',
        158 => 'Sundry',
        159 => 'TravelExpensesGeneralAndAdminExpenses',
        160 => 'TravelExpensesSellingExpense',
      ]
    ],
    8 => [
      'name' => 'Other Expense',
      'subTypes' => [
        161 => 'Depreciation',
        162 => 'ExchangeGainOrLoss',
        163 => 'OtherMiscellaneousExpense',
        164 => 'PenaltiesSettlements',
        165 => 'Amortization',
        166 => 'GasAndFuel',
        167 => 'HomeOffice',
        168 => 'HomeOwnerRentalInsurance',
        169 => 'OtherHomeOfficeExpenses',
        170 => 'MortgageInterest',
        171 => 'RentAndLease',
        172 => 'RepairsAndMaintenance',
        173 => 'ParkingAndTolls',
        174 => 'Vehicle',
        175 => 'VehicleInsurance',
        176 => 'VehicleLease',
        177 => 'VehicleLoanInterest',
        178 => 'VehicleLoan',
        179 => 'VehicleRegistration',
        180 => 'VehicleRepairs',
        181 => 'OtherVehicleExpenses',
        182 => 'UtilitiesHomeOffice', // QBO's doc is wrong, again...
        183 => 'WashAndRoadServices',
        184 => 'DeferredTaxExpense',
        185 => 'Depletion',
        186 => 'ExceptionalItems',
        187 => 'ExtraordinaryItems',
        188 => 'IncomeTaxOtherExpense',
        189 => 'MatCredit',
        190 => 'PriorPeriodItems',
        191 => 'TaxRoundoffGainOrLoss',
      ]
    ],
    9 => [
      'name' => 'Cost of Goods Sold',
      'subTypes' => [
        192 => 'EquipmentRentalCos',
        193 => 'OtherCostsOfServiceCos',
        194 => 'ShippingFreightDeliveryCos',
        195 => 'SuppliesMaterialsCogs',
        196 => 'CostOfLaborCos',
        197 => 'CostOfSales',
        198 => 'FreightAndDeliveryCost',
      ]
    ],
    10 => [
      'name' => 'Accounts Payable',
      'subTypes' => [
        199 => 'AccountsPayable',
        200 => 'OutstandingDuesMicroSmallEnterprise',
        201 => 'OutstandingDuesOtherThanMicroSmallEnterprise',
      ]
    ],
    11 => [
      'name' => 'Credit Card',
      'subTypes' => [
        202 => 'CreditCard',
      ]
    ],
    12 => [
      'name' => 'Long Term Liability',
      'subTypes' => [
        203 => 'NotesPayable',
        204 => 'OtherLongTermLiabilities',
        205 => 'ShareholderNotesPayable',
        206 => 'AccrualsAndDeferredIncome',
        207 => 'AccruedLongLermLiabilities',
        208 => 'AccruedVacationPayable',
        209 => 'BankLoans',
        210 => 'DebtsRelatedToParticipatingInterests',
        211 => 'DeferredTaxLiabilities',
        212 => 'GovernmentAndOtherPublicAuthorities',
        213 => 'GroupAndAssociates',
        214 => 'LiabilitiesRelatedToAssetsHeldForSale',
        215 => 'LongTermBorrowings',
        216 => 'LongTermDebit',
        217 => 'LongTermEmployeeBenefitObligations',
        218 => 'ObligationsUnderFinanceLeases',
        219 => 'OtherLongTermProvisions',
        220 => 'ProvisionForLiabilities',
        221 => 'ProvisionsNonCurrentLiabilities',
        222 => 'StaffAndRelatedLongTermLiabilityAccounts',
      ]
    ],
    13 => [
      'name' => 'Other Current Liability',
      'subTypes' => [
        223 => 'DirectDepositPayable',
        224 => 'LineOfCredit',
        225 => 'LoanPayable',
        226 => 'GlobalTaxPayable',
        227 => 'GlobalTaxSuspense',
        228 => 'OtherCurrentLiabilities',
        229 => 'PayrollClearing',
        230 => 'PayrollTaxPayable',
        231 => 'PrepaidExpensesPayable',
        232 => 'RentsInTrustLiability',
        233 => 'TrustAccountsLiabilities',
        234 => 'FederalIncomeTaxPayable',
        235 => 'InsurancePayable',
        236 => 'SalesTaxPayable',
        237 => 'StateLocalIncomeTaxPayable',
        238 => 'AccruedLiabilities',
        239 => 'CurrentLiabilities',
        240 => 'CurrentPortionEmployeeBenefitsObligations',
        241 => 'CurrentPortionOfObligationsUnderFinanceLeases',
        242 => 'CurrentTaxLiability',
        243 => 'DividendsPayable',
        244 => 'DutiesAndTaxes',
        245 => 'InterestPayables',
        246 => 'ProvisionForWarrantyObligations',
        247 => 'ProvisionsCurrentLiabilities',
        248 => 'ShortTermBorrowings',
        249 => 'SocialSecurityAgencies',
        250 => 'StaffAndRelatedLiabilityAccounts',
        251 => 'SundryDebtorsAndCreditors',
        252 => 'TradeAndOtherPayables',
      ]
    ],
    14 => [
      'name' => 'Income',
      'subTypes' => [
        253 => 'NonProfitIncome',
        254 => 'OtherPrimaryIncome',
        255 => 'SalesOfProductIncome',
        256 => 'ServiceFeeIncome',
        257 => 'DiscountsRefundsGiven',
        258 => 'UnappliedCashPaymentIncome',
        259 => 'CashReceiptIncome',
        260 => 'OperatingGrants',
        261 => 'OtherCurrentOperatingIncome',
        262 => 'OwnWorkCapitalized',
        263 => 'RevenueGeneral',
        264 => 'SalesRetail',
        265 => 'SalesWholesale',
        266 => 'SavingsByTaxScheme'
      ]
    ],
    15 => [
      'name' => 'Other Income',
      'subTypes' => [
        267 => 'DividendIncome',
        268 => 'InterestEarned',
        269 => 'OtherInvestmentIncome',
        270 => 'OtherMiscellaneousIncome',
        271 => 'TaxExemptInterest',
        272 => 'GainLossOnSaleOfFixedAssets',
        273 => 'GainLossOnSaleOfInvestments',
        274 => 'LossOnDisposalOfAssets',
        275 => 'OtherOperatingIncome',
        276 => 'UnrealisedLossOnSecuritiesNetOfTax',
      ]
    ],
  ],
  'restrictedType' => [
    5 => 'Accounts Receivable',
    10 => 'Accounts Payable',
  ],
];
